from __future__ import annotations

import logging
from typing import Any, Dict

import pandas as pd
from ib_insync import IB, Stock
from sqlmodel import Session

from app.core.orders import place_bracket_buy
from app.models.strategy_run import StrategyRun
from app.models.trade import Trade
from app.services.market_data import DataSource, fetch_historical_data

logger = logging.getLogger(__name__)


def _prepare_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    prepared = df.copy()
    prepared.columns = [col.lower() for col in prepared.columns]
    if "date" in prepared.columns:
        prepared = prepared.sort_values("date")
    elif "datetime" in prepared.columns:
        prepared = prepared.sort_values("datetime")
    return prepared.reset_index(drop=True)


def run_high(
    ib: IB,
    layer_cfg: Dict[str, Any],
    equity_budget: float,
    *,
    session: Session,
    strategy_run: StrategyRun,
    layer_name: str = "high",
    simulate: bool = False,
    market_source: DataSource | None = None,
) -> int:
    universe = layer_cfg.get("universe", [])
    if not universe:
        logger.warning("High layer universe is empty; skipping")
        return 0

    allocation_per_trade = equity_budget * 0.005
    trades_created = 0

    for symbol in universe:
        logger.info("Evaluating high-risk strategy for %s", symbol)

        if simulate:
            history = fetch_historical_data(symbol, days=7, interval="5m", source=market_source)
            if history.is_empty():
                logger.warning("No intraday data for %s via %s", symbol, market_source or "default source")
                continue
            time_col = "Date" if "Date" in history.columns else history.columns[0]
            df = pd.DataFrame(history.sort(time_col).to_dicts())
        else:
            contract = Stock(symbol, "SMART", "USD")
            ib.qualifyContracts(contract)
            bars = ib.reqHistoricalData(
                contract,
                endDateTime="",
                durationStr="1 D",
                barSizeSetting="5 mins",
                whatToShow="TRADES",
                useRTH=True,
            )
            if len(bars) < 20:
                logger.warning("Not enough bars for %s", symbol)
                continue
            df = pd.DataFrame([bar.__dict__ for bar in bars])

        df = _prepare_dataframe(df)

        if len(df) < 20:
            logger.warning("Insufficient bars for %s (found %s)", symbol, len(df))
            continue

        df["vwap"] = (df["close"] * df["volume"]).cumsum() / df["volume"].cumsum()
        df["high12"] = df["high"].rolling(12).max()
        df["low12"] = df["low"].rolling(12).min()
        df["atr"] = (df["high"] - df["low"]).rolling(14).mean()

        latest = df.iloc[-1]

        if latest["close"] > latest["high12"] and latest["close"] > latest["vwap"]:
            atr = latest["atr"]
            entry = latest["close"]
            stop = entry - 1.2 * atr
            take = entry + 2.5 * atr
            risk_per_share = entry - stop
            quantity = int(allocation_per_trade / max(risk_per_share, 0.01))

            if quantity > 0:
                if simulate:
                    logger.info(
                        "Simulated high-risk signal %s qty=%s entry=%.2f",
                        symbol,
                        quantity,
                        entry,
                    )
                else:
                    logger.info(
                        "Placing high-risk order %s qty=%s entry=%.2f",
                        symbol,
                        quantity,
                        entry,
                    )

                statuses = place_bracket_buy(
                    ib,
                    symbol,
                    quantity,
                    entry,
                    stop,
                    take,
                    simulate=simulate,
                )
                order_status = statuses[0].status if statuses else ("simulated" if simulate else None)

                notes = (
                    "Simulated signal - no live order executed"
                    if simulate
                    else "Auto-generated by run_high"
                )

                trade = Trade(
                    symbol=symbol,
                    layer=layer_name,
                    strategy="high_intraday",
                    side="BUY",
                    qty=quantity,
                    entry_price=entry,
                    budget_allocated=allocation_per_trade,
                    entry_signal="intraday_breakout_vwap",
                    order_status=order_status,
                    signal_snapshot={
                        "vwap": float(latest["vwap"]),
                        "high12": float(latest["high12"]),
                        "low12": float(latest["low12"]),
                        "atr": float(atr),
                        "simulate": simulate,
                    },
                    strategy_run_id=strategy_run.id,
                    notes=notes,
                )
                session.add(trade)
                trades_created += 1

    return trades_created

