from __future__ import annotations

import logging
from typing import Any, Dict

import pandas as pd
from ib_insync import IB, Stock
from sqlmodel import Session

from app.core.orders import place_bracket_buy
from app.models.strategy_run import StrategyRun
from app.models.trade import Trade
from app.services.market_data import DataSource, fetch_historical_data

logger = logging.getLogger(__name__)


def _prepare_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize dataframe columns for indicator calculations."""
    normalized = df.copy()
    normalized.columns = [col.lower() for col in normalized.columns]

    if "date" in normalized.columns:
        normalized = normalized.sort_values("date")
    elif "datetime" in normalized.columns:
        normalized = normalized.sort_values("datetime")

    return normalized.reset_index(drop=True)


def run_medium(
    ib: IB,
    layer_cfg: Dict[str, Any],
    equity_budget: float,
    *,
    session: Session,
    strategy_run: StrategyRun,
    layer_name: str = "medium",
    simulate: bool = False,
    market_source: DataSource | None = None,
) -> int:
    universe = layer_cfg.get("universe", [])
    if not universe:
        logger.warning("Medium layer universe is empty; skipping")
        return 0

    allocation_per_trade = equity_budget * 0.01
    trades_created = 0

    for symbol in universe:
        logger.info("Evaluating medium strategy for %s", symbol)

        if simulate:
            history = fetch_historical_data(symbol, days=90, interval="1d", source=market_source)
            if history.is_empty():
                logger.warning("No historical data for %s via %s", symbol, market_source or "default source")
                continue
            time_col = "Date" if "Date" in history.columns else history.columns[0]
            df = pd.DataFrame(history.sort(time_col).to_dicts())
        else:
            contract = Stock(symbol, "SMART", "USD")
            ib.qualifyContracts(contract)
            bars = ib.reqHistoricalData(
                contract,
                endDateTime="",
                durationStr="2 M",
                barSizeSetting="1 day",
                whatToShow="TRADES",
                useRTH=True,
            )
            if not bars:
                logger.warning("No historical data for %s", symbol)
                continue
            df = pd.DataFrame([bar.__dict__ for bar in bars])

        df = _prepare_dataframe(df)

        if len(df) < 50:
            logger.warning("Insufficient bars for %s (found %s)", symbol, len(df))
            continue

        df["ema20"] = df["close"].ewm(span=20).mean()
        df["ema50"] = df["close"].ewm(span=50).mean()
        df["high10"] = df["high"].rolling(10).max()
        df["atr"] = (df["high"] - df["low"]).rolling(14).mean()

        latest = df.iloc[-1]
        previous = df.iloc[-2]

        if latest["ema20"] > latest["ema50"] and latest["close"] > previous["high10"]:
            atr = latest["atr"]
            close_price = latest["close"]
            stop = close_price - 1.5 * atr
            take = close_price + 3 * atr
            risk_per_share = close_price - stop
            quantity = int(allocation_per_trade / max(risk_per_share, 0.01))

            if quantity > 0:
                if simulate:
                    logger.info(
                        "Simulated medium swing signal %s qty=%s close=%.2f",
                        symbol,
                        quantity,
                        close_price,
                    )
                else:
                    logger.info(
                        "Placing medium swing order %s qty=%s close=%.2f",
                        symbol,
                        quantity,
                        close_price,
                    )

                statuses = place_bracket_buy(
                    ib,
                    symbol,
                    quantity,
                    close_price,
                    stop,
                    take,
                    simulate=simulate,
                )
                order_status = statuses[0].status if statuses else ("simulated" if simulate else None)

                notes = (
                    "Simulated signal - no live order executed"
                    if simulate
                    else "Auto-generated by run_medium"
                )

                trade = Trade(
                    symbol=symbol,
                    layer=layer_name,
                    strategy="medium_swing",
                    side="BUY",
                    qty=quantity,
                    entry_price=close_price,
                    budget_allocated=allocation_per_trade,
                    entry_signal="ema20_gt_ema50_breakout",
                    order_status=order_status,
                    signal_snapshot={
                        "ema20": float(latest["ema20"]),
                        "ema50": float(latest["ema50"]),
                        "high10_prev": float(previous["high10"]),
                        "atr": float(atr),
                        "simulate": simulate,
                    },
                    strategy_run_id=strategy_run.id,
                    notes=notes,
                )
                session.add(trade)
                trades_created += 1

    return trades_created

