"""Shared base classes and dataclasses for strategies"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Callable, Dict, Literal, Optional


SignalSide = Literal["buy", "sell"]


@dataclass
class TradeSignal:
    """Represents an actionable trading signal generated by a strategy."""

    symbol: str
    timestamp: datetime
    side: SignalSide
    entry_price: float
    confidence: float = 1.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    qty: Optional[float] = None
    risk_percent: Optional[float] = None
    holding_period_minutes: Optional[int] = None
    target_weight: Optional[float] = None  # For allocation strategies
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseBacktestStrategy:
    """Base class for all backtesting strategies."""

    version: str = "base"
    description: str = "Base backtesting strategy"

    def generate_signals(
        self,
        symbol: str,
        bars: list[Any],
        *,
        params: dict,
    ) -> list[TradeSignal]:
        """
        Generate trading signals for a single symbol.

        Args:
            symbol: Ticker symbol
            bars: List of NormalizedBar objects
            params: Strategy parameters

        Returns:
            List of TradeSignal objects
        """

        raise NotImplementedError


class StrategyRegistry:
    """Registry helper to keep track of available strategies."""

    def __init__(self) -> None:
        self._registry: Dict[str, Callable[[], BaseBacktestStrategy]] = {}

    def register(self, cls: type[BaseBacktestStrategy]) -> type[BaseBacktestStrategy]:
        if cls.version in self._registry:
            raise ValueError(f"Strategy version '{cls.version}' already registered")
        self._registry[cls.version] = cls  # type: ignore[assignment]
        return cls

    def get(self, version: str) -> BaseBacktestStrategy:
        if version not in self._registry:
            raise KeyError(f"Strategy '{version}' not found. Available: {list(self._registry.keys())}")
        return self._registry[version]()

    def list_versions(self) -> list[str]:
        return sorted(self._registry.keys())


strategy_registry = StrategyRegistry()
